# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DPD_v1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import platform

if platform.system() == "Windows":
    #주모니터 배율 적용(반드시 배율 미적용보다 우선 실행)
    import tkinter
    resolution = tkinter.Tk()
    resolution.withdraw()
    width_m = resolution.winfo_screenwidth()
    height_m = resolution.winfo_screenheight()

    #주모니터 배율 미적용
    import ctypes
    user32 = ctypes.windll.user32
    user32.SetProcessDPIAware()
    width = user32.GetSystemMetrics(0)
    height = user32.GetSystemMetrics(1)

if platform.system() == "Linux":
    #주모니터 배율 미적용
    import screeninfo
    from screeninfo import get_monitors
    m = get_monitors()
    width, height = [m[0].width, m[0].height]

    #주모니터 배율적용
    import gi
    gi.require_version("Gdk", "3.0")
    from gi.repository import Gdk
    display = Gdk.Display.get_default()
    n_monitors = display.get_n_monitors()
    for m in range(1):
        monitor = display.get_monitor(m)
        geometry = monitor.get_geometry()
        width_m = geometry.width
        height_m = geometry.height

#window        
if width <= 1920: #FHD
    window_w_m = 1.0
    window_h_m = 0.75
elif width <= 2560: #2K
    window_w_m = 1.1*width/width_m
    window_h_m = 0.9*height/height_m
else: #4K
    window_w_m = 1.1*width/width_m
    window_h_m = 0.75*height/height_m

#linux
if width <= 1920: #FHD
    linux_w_m = 1.0
    linux_h_m = 1.0
elif width <= 2560: #2K
    linux_w_m = 1.0
    linux_h_m = 1.0
else: #4K
    linux_w_m = 1.1*width/width_m #2.1 200%
    linux_h_m = 0.75*width/width_m #1.6 200%

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        if platform.system() == "Windows":
            MainWindow.resize(978*window_w_m, 842*window_h_m)
        else:
            MainWindow.resize(978*linux_w_m, 842*linux_h_m)
        #MainWindow.resize(978, 842)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(950, 842))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        # if platform.system() == "Windows":
        #     self.groupBox_6.setMinimumSize(QtCore.QSize(932*window_w_m, 300*window_h_m))
        # else:
        #     self.groupBox_6.setMinimumSize(QtCore.QSize(932*linux_w_m, 300*linux_h_m))
        self.groupBox_6.setMinimumSize(QtCore.QSize(932, 280))

        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(908, 140))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(451, 123))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(104, 25))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(55, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(140, 25))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(105, 25))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(55, 25))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.init_s1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_s1.sizePolicy().hasHeightForWidth())
        self.init_s1.setSizePolicy(sizePolicy)
        self.init_s1.setMinimumSize(QtCore.QSize(104, 25))
        self.init_s1.setAlignment(QtCore.Qt.AlignCenter)
        self.init_s1.setObjectName("init_s1")
        self.gridLayout.addWidget(self.init_s1, 1, 2, 1, 1)
        self.init_s2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_s2.sizePolicy().hasHeightForWidth())
        self.init_s2.setSizePolicy(sizePolicy)
        self.init_s2.setMinimumSize(QtCore.QSize(104, 25))
        self.init_s2.setAlignment(QtCore.Qt.AlignCenter)
        self.init_s2.setObjectName("init_s2")
        self.gridLayout.addWidget(self.init_s2, 2, 2, 1, 1)
        self.init_p1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_p1.sizePolicy().hasHeightForWidth())
        self.init_p1.setSizePolicy(sizePolicy)
        self.init_p1.setMinimumSize(QtCore.QSize(124, 25))
        self.init_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.init_p1.setObjectName("init_p1")
        self.gridLayout.addWidget(self.init_p1, 1, 3, 1, 1)
        self.init_p2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_p2.sizePolicy().hasHeightForWidth())
        self.init_p2.setSizePolicy(sizePolicy)
        self.init_p2.setMinimumSize(QtCore.QSize(124, 25))
        self.init_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.init_p2.setObjectName("init_p2")
        self.gridLayout.addWidget(self.init_p2, 2, 3, 1, 1)
        self.init_r1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_r1.sizePolicy().hasHeightForWidth())
        self.init_r1.setSizePolicy(sizePolicy)
        self.init_r1.setMinimumSize(QtCore.QSize(105, 25))
        self.init_r1.setAlignment(QtCore.Qt.AlignCenter)
        self.init_r1.setObjectName("init_r1")
        self.gridLayout.addWidget(self.init_r1, 1, 4, 1, 1)
        self.init_r2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_r2.sizePolicy().hasHeightForWidth())
        self.init_r2.setSizePolicy(sizePolicy)
        self.init_r2.setMinimumSize(QtCore.QSize(105, 25))
        self.init_r2.setAlignment(QtCore.Qt.AlignCenter)
        self.init_r2.setObjectName("init_r2")
        self.gridLayout.addWidget(self.init_r2, 2, 4, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(455, 123))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(105, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(140, 25))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(104, 25))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(65, 25))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(65, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.min_s = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_s.sizePolicy().hasHeightForWidth())
        self.min_s.setSizePolicy(sizePolicy)
        self.min_s.setMinimumSize(QtCore.QSize(104, 25))
        self.min_s.setAlignment(QtCore.Qt.AlignCenter)
        self.min_s.setObjectName("min_s")
        self.gridLayout_2.addWidget(self.min_s, 1, 1, 1, 1)
        self.max_s = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_s.sizePolicy().hasHeightForWidth())
        self.max_s.setSizePolicy(sizePolicy)
        self.max_s.setMinimumSize(QtCore.QSize(104, 25))
        self.max_s.setAlignment(QtCore.Qt.AlignCenter)
        self.max_s.setObjectName("max_s")
        self.gridLayout_2.addWidget(self.max_s, 2, 1, 1, 1)
        self.min_p = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_p.sizePolicy().hasHeightForWidth())
        self.min_p.setSizePolicy(sizePolicy)
        self.min_p.setMinimumSize(QtCore.QSize(140, 25))
        self.min_p.setAlignment(QtCore.Qt.AlignCenter)
        self.min_p.setObjectName("min_p")
        self.gridLayout_2.addWidget(self.min_p, 1, 2, 1, 1)
        self.max_p = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_p.sizePolicy().hasHeightForWidth())
        self.max_p.setSizePolicy(sizePolicy)
        self.max_p.setMinimumSize(QtCore.QSize(140, 25))
        self.max_p.setAlignment(QtCore.Qt.AlignCenter)
        self.max_p.setObjectName("max_p")
        self.gridLayout_2.addWidget(self.max_p, 2, 2, 1, 1)
        self.min_r = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_r.sizePolicy().hasHeightForWidth())
        self.min_r.setSizePolicy(sizePolicy)
        self.min_r.setMinimumSize(QtCore.QSize(105, 25))
        self.min_r.setAlignment(QtCore.Qt.AlignCenter)
        self.min_r.setObjectName("min_r")
        self.gridLayout_2.addWidget(self.min_r, 1, 3, 1, 1)
        self.max_r = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_r.sizePolicy().hasHeightForWidth())
        self.max_r.setSizePolicy(sizePolicy)
        self.max_r.setMinimumSize(QtCore.QSize(105, 25))
        self.max_r.setAlignment(QtCore.Qt.AlignCenter)
        self.max_r.setObjectName("max_r")
        self.gridLayout_2.addWidget(self.max_r, 2, 3, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(908, 67))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(75, 25))
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.ebg_a = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ebg_a.sizePolicy().hasHeightForWidth())
        self.ebg_a.setSizePolicy(sizePolicy)
        self.ebg_a.setMinimumSize(QtCore.QSize(210, 25))
        self.ebg_a.setAlignment(QtCore.Qt.AlignCenter)
        self.ebg_a.setObjectName("ebg_a")
        self.horizontalLayout_3.addWidget(self.ebg_a)
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(75, 25))
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.ebg_b = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ebg_b.sizePolicy().hasHeightForWidth())
        self.ebg_b.setSizePolicy(sizePolicy)
        self.ebg_b.setMinimumSize(QtCore.QSize(210, 25))
        self.ebg_b.setAlignment(QtCore.Qt.AlignCenter)
        self.ebg_b.setObjectName("ebg_b")
        self.horizontalLayout_3.addWidget(self.ebg_b)
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(75, 25))
        self.label_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.ebg_c = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ebg_c.sizePolicy().hasHeightForWidth())
        self.ebg_c.setSizePolicy(sizePolicy)
        self.ebg_c.setMinimumSize(QtCore.QSize(210, 25))
        self.ebg_c.setAlignment(QtCore.Qt.AlignCenter)
        self.ebg_c.setObjectName("ebg_c")
        self.horizontalLayout_3.addWidget(self.ebg_c)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.remember = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remember.sizePolicy().hasHeightForWidth())
        self.remember.setSizePolicy(sizePolicy)
        self.remember.setMinimumSize(QtCore.QSize(100, 21))
        self.remember.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.remember.setObjectName("remember")
        self.verticalLayout.addWidget(self.remember)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)

        # if platform.system() == "Windows":
        #     self.widget_7.setMinimumSize(QtCore.QSize(0, 80*window_h_m))
        # else:
        #     self.widget_7.setMinimumSize(QtCore.QSize(0, 80*linux_h_m))
        self.widget_7.setMinimumSize(QtCore.QSize(0, 67))

        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(650, 67))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(100, 25))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.goal_gr = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goal_gr.sizePolicy().hasHeightForWidth())
        self.goal_gr.setSizePolicy(sizePolicy)
        self.goal_gr.setMinimumSize(QtCore.QSize(100, 25))
        self.goal_gr.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_gr.setObjectName("goal_gr")
        self.horizontalLayout_9.addWidget(self.goal_gr)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(210, 25))
        self.label_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.goal_bde = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goal_bde.sizePolicy().hasHeightForWidth())
        self.goal_bde.setSizePolicy(sizePolicy)
        self.goal_bde.setMinimumSize(QtCore.QSize(210, 25))
        self.goal_bde.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_bde.setObjectName("goal_bde")
        self.horizontalLayout_9.addWidget(self.goal_bde)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.iteration_1 = QtWidgets.QRadioButton(self.groupBox_10)
        self.iteration_1.setMinimumSize(QtCore.QSize(0, 25))
        self.iteration_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.iteration_1.setChecked(True)
        self.iteration_1.setObjectName("iteration_1")
        self.horizontalLayout_10.addWidget(self.iteration_1)
        self.iteration_2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.iteration_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.iteration_2.setObjectName("iteration_2")
        self.horizontalLayout_10.addWidget(self.iteration_2)
        self.iteration_3 = QtWidgets.QRadioButton(self.groupBox_10)
        self.iteration_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.iteration_3.setObjectName("iteration_3")
        self.horizontalLayout_10.addWidget(self.iteration_3)
        self.horizontalLayout_7.addWidget(self.groupBox_10)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)

        # if platform.system() == "Windows":
        #     self.groupBox_7.setMinimumSize(QtCore.QSize(932, 354*window_h_m))
        # else:
        #     self.groupBox_7.setMinimumSize(QtCore.QSize(932, 354*linux_h_m))
        self.groupBox_7.setMinimumSize(QtCore.QSize(932, 354))

        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(908, 25))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_28 = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(130, 25))
        self.label_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_2.addWidget(self.label_28)
        self.optimization = QtWidgets.QLineEdit(self.widget_3)
        self.optimization.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimization.sizePolicy().hasHeightForWidth())
        self.optimization.setSizePolicy(sizePolicy)
        self.optimization.setMinimumSize(QtCore.QSize(772, 25))
        self.optimization.setAlignment(QtCore.Qt.AlignCenter)
        self.optimization.setReadOnly(True)
        self.optimization.setObjectName("optimization")
        self.horizontalLayout_2.addWidget(self.optimization)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(908, 129))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(255, 25))
        self.label_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(100, 25))
        self.label_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(255, 25))
        self.label_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(100, 25))
        self.label_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(256, 25))
        self.label_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 3, 1, 1)
        self.optimal_gr = QtWidgets.QLineEdit(self.groupBox_4)
        self.optimal_gr.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_gr.sizePolicy().hasHeightForWidth())
        self.optimal_gr.setSizePolicy(sizePolicy)
        self.optimal_gr.setMinimumSize(QtCore.QSize(255, 25))
        self.optimal_gr.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_gr.setReadOnly(True)
        self.optimal_gr.setObjectName("optimal_gr")
        self.gridLayout_4.addWidget(self.optimal_gr, 2, 1, 1, 1)
        self.init_fde = QtWidgets.QLineEdit(self.groupBox_4)
        self.init_fde.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_fde.sizePolicy().hasHeightForWidth())
        self.init_fde.setSizePolicy(sizePolicy)
        self.init_fde.setMinimumSize(QtCore.QSize(256, 25))
        self.init_fde.setAlignment(QtCore.Qt.AlignCenter)
        self.init_fde.setReadOnly(True)
        self.init_fde.setObjectName("init_fde")
        self.gridLayout_4.addWidget(self.init_fde, 1, 3, 1, 1)
        self.optimal_fde = QtWidgets.QLineEdit(self.groupBox_4)
        self.optimal_fde.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_fde.sizePolicy().hasHeightForWidth())
        self.optimal_fde.setSizePolicy(sizePolicy)
        self.optimal_fde.setMinimumSize(QtCore.QSize(256, 25))
        self.optimal_fde.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_fde.setReadOnly(True)
        self.optimal_fde.setObjectName("optimal_fde")
        self.gridLayout_4.addWidget(self.optimal_fde, 2, 3, 1, 1)
        self.init_bde = QtWidgets.QLineEdit(self.groupBox_4)
        self.init_bde.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_bde.sizePolicy().hasHeightForWidth())
        self.init_bde.setSizePolicy(sizePolicy)
        self.init_bde.setMinimumSize(QtCore.QSize(255, 25))
        self.init_bde.setAlignment(QtCore.Qt.AlignCenter)
        self.init_bde.setReadOnly(True)
        self.init_bde.setObjectName("init_bde")
        self.gridLayout_4.addWidget(self.init_bde, 1, 4, 1, 1)
        self.optimal_bde = QtWidgets.QLineEdit(self.groupBox_4)
        self.optimal_bde.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_bde.sizePolicy().hasHeightForWidth())
        self.optimal_bde.setSizePolicy(sizePolicy)
        self.optimal_bde.setMinimumSize(QtCore.QSize(255, 25))
        self.optimal_bde.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_bde.setReadOnly(True)
        self.optimal_bde.setObjectName("optimal_bde")
        self.gridLayout_4.addWidget(self.optimal_bde, 2, 4, 1, 1)
        self.init_gr = QtWidgets.QLineEdit(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_gr.sizePolicy().hasHeightForWidth())
        self.init_gr.setSizePolicy(sizePolicy)
        self.init_gr.setMinimumSize(QtCore.QSize(255, 25))
        self.init_gr.setAlignment(QtCore.Qt.AlignCenter)
        self.init_gr.setReadOnly(True)
        self.init_gr.setObjectName("init_gr")
        self.gridLayout_4.addWidget(self.init_gr, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(908, 150))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setMinimumSize(QtCore.QSize(602, 125))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(168, 25))
        self.label_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(169, 25))
        self.label_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(168, 25))
        self.label_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(55, 25))
        self.label_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(55, 25))
        self.label_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 2, 0, 1, 1)
        self.optimal_s1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.optimal_s1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_s1.sizePolicy().hasHeightForWidth())
        self.optimal_s1.setSizePolicy(sizePolicy)
        self.optimal_s1.setMinimumSize(QtCore.QSize(168, 25))
        self.optimal_s1.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_s1.setReadOnly(True)
        self.optimal_s1.setObjectName("optimal_s1")
        self.gridLayout_6.addWidget(self.optimal_s1, 1, 1, 1, 1)
        self.optimal_s2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.optimal_s2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_s2.sizePolicy().hasHeightForWidth())
        self.optimal_s2.setSizePolicy(sizePolicy)
        self.optimal_s2.setMinimumSize(QtCore.QSize(168, 25))
        self.optimal_s2.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_s2.setReadOnly(True)
        self.optimal_s2.setObjectName("optimal_s2")
        self.gridLayout_6.addWidget(self.optimal_s2, 2, 1, 1, 1)
        self.optimal_p1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.optimal_p1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_p1.sizePolicy().hasHeightForWidth())
        self.optimal_p1.setSizePolicy(sizePolicy)
        self.optimal_p1.setMinimumSize(QtCore.QSize(169, 25))
        self.optimal_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_p1.setReadOnly(True)
        self.optimal_p1.setObjectName("optimal_p1")
        self.gridLayout_6.addWidget(self.optimal_p1, 1, 2, 1, 1)
        self.optimal_p2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.optimal_p2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_p2.sizePolicy().hasHeightForWidth())
        self.optimal_p2.setSizePolicy(sizePolicy)
        self.optimal_p2.setMinimumSize(QtCore.QSize(169, 25))
        self.optimal_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_p2.setReadOnly(True)
        self.optimal_p2.setObjectName("optimal_p2")
        self.gridLayout_6.addWidget(self.optimal_p2, 2, 2, 1, 1)
        self.optimal_r1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.optimal_r1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_r1.sizePolicy().hasHeightForWidth())
        self.optimal_r1.setSizePolicy(sizePolicy)
        self.optimal_r1.setMinimumSize(QtCore.QSize(168, 25))
        self.optimal_r1.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_r1.setReadOnly(True)
        self.optimal_r1.setObjectName("optimal_r1")
        self.gridLayout_6.addWidget(self.optimal_r1, 1, 3, 1, 1)
        self.optimal_r2 = QtWidgets.QLineEdit(self.groupBox_8)
        self.optimal_r2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_r2.sizePolicy().hasHeightForWidth())
        self.optimal_r2.setSizePolicy(sizePolicy)
        self.optimal_r2.setMinimumSize(QtCore.QSize(168, 25))
        self.optimal_r2.setAlignment(QtCore.Qt.AlignCenter)
        self.optimal_r2.setReadOnly(True)
        self.optimal_r2.setObjectName("optimal_r2")
        self.gridLayout_6.addWidget(self.optimal_r2, 2, 3, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_8)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 150))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(276, 25))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(75, 25))
        self.label_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_6.addWidget(self.label_21)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cc_gr = QtWidgets.QLineEdit(self.widget_6)
        self.cc_gr.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_gr.sizePolicy().hasHeightForWidth())
        self.cc_gr.setSizePolicy(sizePolicy)
        self.cc_gr.setMinimumSize(QtCore.QSize(195, 25))
        self.cc_gr.setAlignment(QtCore.Qt.AlignCenter)
        self.cc_gr.setReadOnly(True)
        self.cc_gr.setObjectName("cc_gr")
        self.verticalLayout_5.addWidget(self.cc_gr)
        self.cc_gr_f = QtWidgets.QLineEdit(self.widget_6)
        self.cc_gr_f.setMinimumSize(QtCore.QSize(195, 25))
        self.cc_gr_f.setAlignment(QtCore.Qt.AlignCenter)
        self.cc_gr_f.setObjectName("cc_gr_f")
        self.verticalLayout_5.addWidget(self.cc_gr_f)
        self.horizontalLayout_6.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.frame = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(276, 25))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(160, 25))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.cc_3_L = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_3_L.sizePolicy().hasHeightForWidth())
        self.cc_3_L.setSizePolicy(sizePolicy)
        self.cc_3_L.setMinimumSize(QtCore.QSize(73, 20))
        self.cc_3_L.setAlignment(QtCore.Qt.AlignCenter)
        self.cc_3_L.setReadOnly(True)
        self.cc_3_L.setObjectName("cc_3_L")
        self.horizontalLayout_8.addWidget(self.cc_3_L)
        self.cc_3 = QtWidgets.QCheckBox(self.frame)
        self.cc_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_3.sizePolicy().hasHeightForWidth())
        self.cc_3.setSizePolicy(sizePolicy)
        self.cc_3.setMinimumSize(QtCore.QSize(23, 25))
        self.cc_3.setMouseTracking(True)
        self.cc_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cc_3.setStatusTip("")
        self.cc_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cc_3.setText("")
        self.cc_3.setCheckable(True)
        self.cc_3.setChecked(False)
        self.cc_3.setObjectName("cc_3")
        self.horizontalLayout_8.addWidget(self.cc_3)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(276, 25))
        self.frame_2.setMouseTracking(True)
        self.frame_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_29 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(160, 25))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_12.addWidget(self.label_29)
        self.cc_4_L = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_4_L.sizePolicy().hasHeightForWidth())
        self.cc_4_L.setSizePolicy(sizePolicy)
        self.cc_4_L.setMinimumSize(QtCore.QSize(73, 20))
        self.cc_4_L.setAlignment(QtCore.Qt.AlignCenter)
        self.cc_4_L.setReadOnly(True)
        self.cc_4_L.setObjectName("cc_4_L")
        self.horizontalLayout_12.addWidget(self.cc_4_L)
        self.cc_4 = QtWidgets.QCheckBox(self.frame_2)
        self.cc_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_4.sizePolicy().hasHeightForWidth())
        self.cc_4.setSizePolicy(sizePolicy)
        self.cc_4.setMinimumSize(QtCore.QSize(23, 25))
        self.cc_4.setMouseTracking(False)
        self.cc_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cc_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cc_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cc_4.setText("")
        self.cc_4.setCheckable(True)
        self.cc_4.setObjectName("cc_4")
        self.horizontalLayout_12.addWidget(self.cc_4)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(276, 25))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_30 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(160, 25))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_11.addWidget(self.label_30)
        self.cc_5_L = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_5_L.sizePolicy().hasHeightForWidth())
        self.cc_5_L.setSizePolicy(sizePolicy)
        self.cc_5_L.setMinimumSize(QtCore.QSize(73, 20))
        self.cc_5_L.setAlignment(QtCore.Qt.AlignCenter)
        self.cc_5_L.setReadOnly(True)
        self.cc_5_L.setObjectName("cc_5_L")
        self.horizontalLayout_11.addWidget(self.cc_5_L)
        self.cc_5 = QtWidgets.QCheckBox(self.frame_3)
        self.cc_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cc_5.sizePolicy().hasHeightForWidth())
        self.cc_5.setSizePolicy(sizePolicy)
        self.cc_5.setMinimumSize(QtCore.QSize(23, 25))
        self.cc_5.setMouseTracking(True)
        self.cc_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cc_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cc_5.setStatusTip("")
        self.cc_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cc_5.setText("")
        self.cc_5.setCheckable(True)
        self.cc_5.setObjectName("cc_5")
        self.horizontalLayout_11.addWidget(self.cc_5)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(932, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.optimal_Button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_Button.sizePolicy().hasHeightForWidth())
        self.optimal_Button.setSizePolicy(sizePolicy)
        self.optimal_Button.setMinimumSize(QtCore.QSize(85, 25))
        self.optimal_Button.setObjectName("optimal_Button")
        self.horizontalLayout.addWidget(self.optimal_Button)
        self.quit_Button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_Button.sizePolicy().hasHeightForWidth())
        self.quit_Button.setSizePolicy(sizePolicy)
        self.quit_Button.setMinimumSize(QtCore.QSize(85, 25))
        self.quit_Button.setObjectName("quit_Button")
        self.horizontalLayout.addWidget(self.quit_Button)
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Optimal Gear Ratio Calculation Tool by DRCL(기어비 우선 버전)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Initialization"))
        self.groupBox.setTitle(_translate("MainWindow", "Initial Value"))
        self.label_2.setText(_translate("MainWindow", "Sun Gear [mm]"))
        self.label.setText(_translate("MainWindow", "First"))
        self.label_3.setText(_translate("MainWindow", "Planetary Gear [mm]"))
        self.label_4.setText(_translate("MainWindow", "Ring Gear [mm]"))
        self.label_5.setText(_translate("MainWindow", "Second"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Boundary Condition"))
        self.label_8.setText(_translate("MainWindow", "Ring Gear [mm]"))
        self.label_7.setText(_translate("MainWindow", "Planetary Gear [mm]"))
        self.label_6.setText(_translate("MainWindow", "Sun Gear [mm]"))
        self.label_9.setText(_translate("MainWindow", "Minimum"))
        self.label_10.setText(_translate("MainWindow", "Maximum"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Efficiency between Gears"))
        self.label_18.setText(_translate("MainWindow", "ηa(S1, P1)"))
        self.label_19.setText(_translate("MainWindow", "ηb(P1, R1)"))
        self.label_20.setText(_translate("MainWindow", "ηc(P2, R2)"))
        self.remember.setText(_translate("MainWindow", "Remember initialization setting"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Goal Value"))
        self.label_14.setText(_translate("MainWindow", "Gear Ratio"))
        self.label_12.setText(_translate("MainWindow", "Backward Drive Efficiency [%]"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Maximum iteration of optimization"))
        self.iteration_1.setText(_translate("MainWindow", "1000"))
        self.iteration_2.setText(_translate("MainWindow", "5000"))
        self.iteration_3.setText(_translate("MainWindow", "10000"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Optimization Result"))
        self.label_28.setText(_translate("MainWindow", "Optimization Result"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Comparison"))
        self.label_11.setText(_translate("MainWindow", "Gear Ratio"))
        self.label_17.setText(_translate("MainWindow", "Optimal Result"))
        self.label_15.setText(_translate("MainWindow", "Backward Drive Efficiency [%]"))
        self.label_16.setText(_translate("MainWindow", "Initial State"))
        self.label_13.setText(_translate("MainWindow", "Forward Drive Efficiency [%]"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Optimal Result"))
        self.label_23.setText(_translate("MainWindow", "Ring Gear [mm]"))
        self.label_24.setText(_translate("MainWindow", "Planetary Gear [mm]"))
        self.label_25.setText(_translate("MainWindow", "Sun Gear [mm]"))
        self.label_26.setText(_translate("MainWindow", "First"))
        self.label_27.setText(_translate("MainWindow", "Second"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Constraint Confirmation"))
        self.label_21.setText(_translate("MainWindow", "Gear Ratio"))
        self.label_22.setText(_translate("MainWindow", "R1 - S1 - 2*P1 = 0"))
        self.label_29.setText(_translate("MainWindow", "R2 - S2 -2*P2 = 0"))
        self.label_30.setText(_translate("MainWindow", "(S1 + P1) - (S2 + P2) = 0"))
        self.optimal_Button.setText(_translate("MainWindow", "Optimization"))
        self.quit_Button.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

