# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OGRCT_m4.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import platform

if platform.system() == "Windows":
    #주모니터 배율 적용(반드시 배율 미적용보다 우선 실행)
    import tkinter
    resolution = tkinter.Tk()
    resolution.withdraw()
    width_m = resolution.winfo_screenwidth()
    height_m = resolution.winfo_screenheight()

    #주모니터 배율 미적용
    import ctypes
    user32 = ctypes.windll.user32
    user32.SetProcessDPIAware()
    width = user32.GetSystemMetrics(0)
    height = user32.GetSystemMetrics(1)

if platform.system() == "Linux":
    #주모니터 배율 미적용
    import screeninfo
    from screeninfo import get_monitors
    m = get_monitors()
    width = m[0].width
    height = m[0].height

    #주모니터 배율적용
    import gi
    gi.require_version("Gdk", "3.0")
    from gi.repository import Gdk
    display = Gdk.Display.get_default()
    n_monitors = display.get_n_monitors()
    for m in range(1):
        monitor = display.get_monitor(m)
        geometry = monitor.get_geometry()
        width_m = geometry.width
        height_m = geometry.height

#window
if width <= 1920: #FHD
    window_w_m = 1.6
    window_h_m = 1.2
elif width <= 2560: #2K
    window_w_m = 1.6*width/width_m
    window_h_m = 1.1*height/height_m
else: #4K
    window_w_m = 1.3*width/width_m
    window_h_m = 1.0*height/height_m

#linux
if width <= 1920: #FHD
    linux_w_m = 1.3
    linux_h_m = 0.9
elif width <= 2560: #2K
    linux_w_m = 1.3
    linux_h_m = 0.9
else: #4K
    linux_w_m = 1.3*width/width_m
    linux_h_m = 0.9*height/height_m

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1576, 1130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)

        if platform.system() == "Windows":
            MainWindow.resize(950*window_w_m, 850*window_h_m)
        else:
            MainWindow.resize(950*linux_w_m, 850*linux_h_m)

        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)

        if platform.system() == "Windows":
            self.groupBox_6.setMinimumSize(QtCore.QSize(932*window_w_m, 300*window_h_m))
        else:
            self.groupBox_6.setMinimumSize(QtCore.QSize(932*linux_w_m, 300*linux_h_m))
        #self.groupBox_6.setMinimumSize(QtCore.QSize(932, 280))

        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(908, 140))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(430, 123))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(65, 25))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.module_2 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_2.sizePolicy().hasHeightForWidth())
        self.module_2.setSizePolicy(sizePolicy)
        self.module_2.setMinimumSize(QtCore.QSize(104, 25))
        self.module_2.setAlignment(QtCore.Qt.AlignCenter)
        self.module_2.setObjectName("module_2")
        self.gridLayout.addWidget(self.module_2, 3, 2, 1, 1)
        self.module_1 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_1.sizePolicy().hasHeightForWidth())
        self.module_1.setSizePolicy(sizePolicy)
        self.module_1.setMinimumSize(QtCore.QSize(80, 25))
        self.module_1.setAlignment(QtCore.Qt.AlignCenter)
        self.module_1.setObjectName("module_1")
        self.gridLayout.addWidget(self.module_1, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(55, 25))
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(65, 25))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(65, 25))
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.module_3 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_3.sizePolicy().hasHeightForWidth())
        self.module_3.setSizePolicy(sizePolicy)
        self.module_3.setMinimumSize(QtCore.QSize(104, 25))
        self.module_3.setAlignment(QtCore.Qt.AlignCenter)
        self.module_3.setObjectName("module_3")
        self.gridLayout.addWidget(self.module_3, 4, 2, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(455, 123))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(105, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(140, 25))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(104, 25))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 1, 1, 1)
        self.min_s = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_s.sizePolicy().hasHeightForWidth())
        self.min_s.setSizePolicy(sizePolicy)
        self.min_s.setMinimumSize(QtCore.QSize(104, 25))
        self.min_s.setAlignment(QtCore.Qt.AlignCenter)
        self.min_s.setObjectName("min_s")
        self.gridLayout_2.addWidget(self.min_s, 1, 1, 1, 1)
        self.max_s = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_s.sizePolicy().hasHeightForWidth())
        self.max_s.setSizePolicy(sizePolicy)
        self.max_s.setMinimumSize(QtCore.QSize(104, 25))
        self.max_s.setAlignment(QtCore.Qt.AlignCenter)
        self.max_s.setObjectName("max_s")
        self.gridLayout_2.addWidget(self.max_s, 2, 1, 1, 1)
        self.min_p = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_p.sizePolicy().hasHeightForWidth())
        self.min_p.setSizePolicy(sizePolicy)
        self.min_p.setMinimumSize(QtCore.QSize(140, 25))
        self.min_p.setAlignment(QtCore.Qt.AlignCenter)
        self.min_p.setObjectName("min_p")
        self.gridLayout_2.addWidget(self.min_p, 1, 2, 1, 1)
        self.max_p = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_p.sizePolicy().hasHeightForWidth())
        self.max_p.setSizePolicy(sizePolicy)
        self.max_p.setMinimumSize(QtCore.QSize(140, 25))
        self.max_p.setAlignment(QtCore.Qt.AlignCenter)
        self.max_p.setObjectName("max_p")
        self.gridLayout_2.addWidget(self.max_p, 2, 2, 1, 1)
        self.min_r = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_r.sizePolicy().hasHeightForWidth())
        self.min_r.setSizePolicy(sizePolicy)
        self.min_r.setMinimumSize(QtCore.QSize(105, 25))
        self.min_r.setAlignment(QtCore.Qt.AlignCenter)
        self.min_r.setObjectName("min_r")
        self.gridLayout_2.addWidget(self.min_r, 1, 3, 1, 1)
        self.max_r = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_r.sizePolicy().hasHeightForWidth())
        self.max_r.setSizePolicy(sizePolicy)
        self.max_r.setMinimumSize(QtCore.QSize(105, 25))
        self.max_r.setAlignment(QtCore.Qt.AlignCenter)
        self.max_r.setObjectName("max_r")
        self.gridLayout_2.addWidget(self.max_r, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 25))
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 25))
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(908, 67))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(75, 25))
        self.label_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.ebg_a = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ebg_a.sizePolicy().hasHeightForWidth())
        self.ebg_a.setSizePolicy(sizePolicy)
        self.ebg_a.setMinimumSize(QtCore.QSize(210, 25))
        self.ebg_a.setAlignment(QtCore.Qt.AlignCenter)
        self.ebg_a.setObjectName("ebg_a")
        self.horizontalLayout_3.addWidget(self.ebg_a)
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(75, 25))
        self.label_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_3.addWidget(self.label_19)
        self.ebg_b = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ebg_b.sizePolicy().hasHeightForWidth())
        self.ebg_b.setSizePolicy(sizePolicy)
        self.ebg_b.setMinimumSize(QtCore.QSize(210, 25))
        self.ebg_b.setAlignment(QtCore.Qt.AlignCenter)
        self.ebg_b.setObjectName("ebg_b")
        self.horizontalLayout_3.addWidget(self.ebg_b)
        self.label_20 = QtWidgets.QLabel(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(75, 25))
        self.label_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_3.addWidget(self.label_20)
        self.ebg_c = QtWidgets.QLineEdit(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ebg_c.sizePolicy().hasHeightForWidth())
        self.ebg_c.setSizePolicy(sizePolicy)
        self.ebg_c.setMinimumSize(QtCore.QSize(210, 25))
        self.ebg_c.setAlignment(QtCore.Qt.AlignCenter)
        self.ebg_c.setObjectName("ebg_c")
        self.horizontalLayout_3.addWidget(self.ebg_c)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.remember = QtWidgets.QCheckBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remember.sizePolicy().hasHeightForWidth())
        self.remember.setSizePolicy(sizePolicy)
        self.remember.setMinimumSize(QtCore.QSize(100, 21))
        self.remember.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.remember.setObjectName("remember")
        self.verticalLayout.addWidget(self.remember)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        
        if platform.system() == "Windows":
            self.widget_7.setMinimumSize(QtCore.QSize(0, 80*window_h_m))
        else:
            self.widget_7.setMinimumSize(QtCore.QSize(0, 80*linux_h_m))
        #self.widget_7.setMinimumSize(QtCore.QSize(0, 67))

        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(650, 67))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(80, 25))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.goal_gr = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goal_gr.sizePolicy().hasHeightForWidth())
        self.goal_gr.setSizePolicy(sizePolicy)
        self.goal_gr.setMinimumSize(QtCore.QSize(80, 25))
        self.goal_gr.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.goal_gr.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_gr.setObjectName("goal_gr")
        self.horizontalLayout_9.addWidget(self.goal_gr)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(210, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.goal_bde = QtWidgets.QLineEdit(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goal_bde.sizePolicy().hasHeightForWidth())
        self.goal_bde.setSizePolicy(sizePolicy)
        self.goal_bde.setMinimumSize(QtCore.QSize(100, 25))
        self.goal_bde.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.goal_bde.setAlignment(QtCore.Qt.AlignCenter)
        self.goal_bde.setObjectName("goal_bde")
        self.horizontalLayout_9.addWidget(self.goal_bde)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.iteration_1 = QtWidgets.QRadioButton(self.groupBox_10)
        self.iteration_1.setMinimumSize(QtCore.QSize(0, 25))
        self.iteration_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.iteration_1.setChecked(True)
        self.iteration_1.setObjectName("iteration_1")
        self.horizontalLayout_10.addWidget(self.iteration_1)
        self.iteration_2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.iteration_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.iteration_2.setObjectName("iteration_2")
        self.horizontalLayout_10.addWidget(self.iteration_2)
        self.iteration_3 = QtWidgets.QRadioButton(self.groupBox_10)
        self.iteration_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.iteration_3.setObjectName("iteration_3")
        self.horizontalLayout_10.addWidget(self.iteration_3)
        self.horizontalLayout_7.addWidget(self.groupBox_10)
        self.verticalLayout_2.addWidget(self.widget_7)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)

        if platform.system() == "Windows":
            self.groupBox_7.setMinimumSize(QtCore.QSize(932*window_w_m, 400*window_h_m))
        elif width/width_m >= 2:
            self.groupBox_7.setMinimumSize(QtCore.QSize(932*linux_w_m, 400*linux_h_m))    
        else:
            self.groupBox_7.setMinimumSize(QtCore.QSize(932*linux_w_m, 400*linux_h_m*1.3))
        #self.groupBox_7.setMinimumSize(QtCore.QSize(932, 400))

        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(10)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)

        if platform.system() == "Windows":
            self.tableWidget.setColumnWidth(0,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(1,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(2,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(3,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(4,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(5,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(6,self.tableWidget.width()*1.4*window_w_m)
            self.tableWidget.setColumnWidth(7,self.tableWidget.width()*1.4*window_w_m)
            self.tableWidget.setColumnWidth(8,self.tableWidget.width()*1*window_w_m)
            self.tableWidget.setColumnWidth(9,self.tableWidget.width()*1.4*window_w_m)
            self.tableWidget.setColumnWidth(10,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(11,self.tableWidget.width()/2*window_w_m)
        else:
            self.tableWidget.setColumnWidth(0,self.tableWidget.width()/2*linux_w_m)
            self.tableWidget.setColumnWidth(1,self.tableWidget.width()/2*linux_w_m)
            self.tableWidget.setColumnWidth(2,self.tableWidget.width()/2*linux_w_m)
            self.tableWidget.setColumnWidth(3,self.tableWidget.width()/2*linux_w_m)
            self.tableWidget.setColumnWidth(4,self.tableWidget.width()/2*linux_w_m)
            self.tableWidget.setColumnWidth(5,self.tableWidget.width()/2*linux_w_m)
            self.tableWidget.setColumnWidth(6,self.tableWidget.width()*1.4*linux_w_m)
            self.tableWidget.setColumnWidth(7,self.tableWidget.width()*1.4*linux_w_m)
            self.tableWidget.setColumnWidth(8,self.tableWidget.width()*1*linux_w_m)
            self.tableWidget.setColumnWidth(9,self.tableWidget.width()*1.4*linux_w_m)
            self.tableWidget.setColumnWidth(10,self.tableWidget.width()/2*window_w_m)
            self.tableWidget.setColumnWidth(11,self.tableWidget.width()/2*window_w_m)

        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_2.addWidget(self.groupBox_7)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(932, 35))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.optimal_Button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optimal_Button.sizePolicy().hasHeightForWidth())
        self.optimal_Button.setSizePolicy(sizePolicy)
        self.optimal_Button.setMinimumSize(QtCore.QSize(85, 30))
        self.optimal_Button.setMaximumSize(QtCore.QSize(16777215, 25))
        self.optimal_Button.setObjectName("optimal_Button")
        self.horizontalLayout.addWidget(self.optimal_Button)
        self.quit_Button = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_Button.sizePolicy().hasHeightForWidth())
        self.quit_Button.setSizePolicy(sizePolicy)
        self.quit_Button.setMinimumSize(QtCore.QSize(85, 25))
        self.quit_Button.setMaximumSize(QtCore.QSize(16777215, 25))
        self.quit_Button.setObjectName("quit_Button")
        self.horizontalLayout.addWidget(self.quit_Button)
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Optimal Gear Ratio Calculation Tool by DRCL(모듈 우선 버전)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Initialization"))
        self.groupBox.setTitle(_translate("MainWindow", "Module"))
        self.label_10.setText(_translate("MainWindow", "Maximum"))
        self.label_31.setText(_translate("MainWindow", "Module"))
        self.label_9.setText(_translate("MainWindow", "Minimum"))
        self.label_3.setText(_translate("MainWindow", "Step"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Boundary Condition"))
        self.label_8.setText(_translate("MainWindow", "Ring Gear [mm]"))
        self.label_7.setText(_translate("MainWindow", "Planetary Gear [mm]"))
        self.label_6.setText(_translate("MainWindow", "Sun Gear [mm]"))
        self.label.setText(_translate("MainWindow", "Minimum"))
        self.label_2.setText(_translate("MainWindow", "Maximum"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Efficiency between Gears"))
        self.label_18.setText(_translate("MainWindow", "ηa(S1, P1)"))
        self.label_19.setText(_translate("MainWindow", "ηb(P1, R1)"))
        self.label_20.setText(_translate("MainWindow", "ηc(P2, R2)"))
        self.remember.setText(_translate("MainWindow", "Remember initialization setting"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Goal Value"))
        self.label_14.setText(_translate("MainWindow", "Gear Ratio"))
        self.label_12.setText(_translate("MainWindow", "Backward Drive Efficiency [%]"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Maximum iteration of optimization"))
        self.iteration_1.setText(_translate("MainWindow", "1000"))
        self.iteration_2.setText(_translate("MainWindow", "5000"))
        self.iteration_3.setText(_translate("MainWindow", "10000"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Optimization Result"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "S1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "P1"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "R1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "S2"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "P2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "R2"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Forward Efficiency"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Backward Efficiency"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Gear Ratio"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Gear Ratio Error"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "M1"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "M2"))
        self.optimal_Button.setText(_translate("MainWindow", "Optimization"))
        self.quit_Button.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

